theme: jekyll-theme-minimal
title: Jia's homepage
description: IT case colletion and study
permalink: /:categories/:year/:month/:day/:title/
url: "https://pyff-ny.github.io"
baseurl: ""
author: Jia Li




